### ISSUE TITLE
Create events page

### ISSUE THREAD

**Issue by dPliakos** [ieee-ateith-sb/new_webpage#3]
Modify the `Events` component at /src/events.js to contain the events page.

**Comment by officiallor** [comment]
I got it

**Comment by dPliakos** [comment]
suggested view by @vasal19 
![25529832_10208061235088982_1644512419_n](https://user-images.githubusercontent.com/17273872/35353856-2acfae48-0151-11e8-80a5-5dd79698e8a9.jpg)

**Comment by dPliakos** [comment]
Page is created.
